FROM node

RUN mkdir /app
WORKDIR /app

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY prisma /app/prisma
COPY src /app/src
COPY test /app/test
COPY tsconfig.json /app/tsconfig.json
COPY tsconfig.build.json /app/tsconfig.build.json
COPY nest-cli.json /app/nest-cli.json
RUN npm install

EXPOSE 3000

COPY test.sh /app/test.sh

CMD ["bash", "test.sh"]
