version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: typevocab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -d typevocab -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test

    environment:
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=1d
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/typevocab

    volumes:
      - ~/.aws:/root/.aws
    depends_on:
      db:
        condition: service_healthy
