version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: typevocab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - typevocab:/var/lib/postgresql/data

volumes:
  typevocab:
