@endpoint = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGY4NmI5NTQwOGZmNDQ5MTFmMmFlNGQiLCJpYXQiOjE2OTQ1ODc0MTAsImV4cCI6MTY5NTE5MjIxMH0.aWhyUmbgE1VXcBq8mjiVNRDnwl9HlFNQ_JDb50M5AEw

### POST /folders - Create a new folder
POST {{endpoint}}/folders HTTP/1.1
Cookie: jwt={{jwt}}
Content-Type: application/json

{
    "folderName": "foldername1"
}

### GET /folders - Get all folders
GET {{endpoint}}/folders HTTP/1.1
Cookie: jwt={{jwt}}


### DELETE /folders/:id - Delete a folder
DELETE {{endpoint}}/folders/123 HTTP/1.1
Cookie: jwt={{jwt}}