@endpoint = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ODQxOTA3MTQiLCJpYXQiOjE2OTM0NzcxODUsImV4cCI6MTY5MzU2MzU4NX0.RFobchsoWPs2QAVh04jzDcmxO0-ZJea6fzmJd3jIBEg

# GET /user
GET {{endpoint}}/user
Cookie: jwt={{jwt}}

### 사진 업로드
# POST /user/image
POST {{endpoint}}/user/image
Cookie: jwt={{jwt}}
Content-Type: multipart/form-data; boundary=image-file-upload

--image-file-upload
Content-Disposition: form-data; name="file"; filename="nodejs.png"
Content-Type: image/png

< ../../temp/nodejs.png
--image-file-upload--

### 사진 삭제
# DELETE /user/image
DELETE {{endpoint}}/user/image
Cookie: jwt={{jwt}}