@endpoint = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGY4NmI5NTQwOGZmNDQ5MTFmMmFlNGQiLCJpYXQiOjE2OTQ1ODc0MTAsImV4cCI6MTY5NTE5MjIxMH0.aWhyUmbgE1VXcBq8mjiVNRDnwl9HlFNQ_JDb50M5AEw


### POST /vocab/folder - Create a new folder
POST {{endpoint}}/vocab/folder HTTP/1.1
Cookie: jwt={{jwt}}
Content-Type: application/json

{
    "folderName2": "folder name22"
}


### GET /vocab/folders - Get all folders
GET {{endpoint}}/vocab/folder HTTP/1.1
Cookie: jwt={{jwt}}
Content-Type: application/json


### DELETE /vocab/folder/:folderId - Delete a folder
DELETE {{endpoint}}/vocab/folder/6501b0e490e7d342a348584f HTTP/1.1
Cookie: jwt={{jwt}}


### POST /vocab/vocabulary - Create a new vocabulary
POST {{endpoint}}/vocab/vocabulary HTTP/1.1
Cookie: jwt={{jwt}}
Content-Type: application/json

{
    "folderId": "6501b1f990e7d342a3485859",
    "vocabularyName": "voca2"
}


### DELETE /vocab/vocabulary/:vocabularyId - Delete a vocabulary
DELETE {{endpoint}}/vocab/vocabulary/6501b2c590e7d342a348586b HTTP/1.1
Cookie: jwt={{jwt}}


### POST /vocab/words - Create a new word
POST {{endpoint}}/vocab/words HTTP/1.1
Cookie: jwt={{jwt}}
Content-Type: application/json

{
    "vocabularyId": "6501b27790e7d342a3485863",
    "words": [
        {
            "word": "apple",
            "meaning": "사과"
        }, {
            "word": "banana",
            "meaning": "바나나"
        }
    ]
}


### GET /vocab/words/:vocabularyId - Get all words
GET {{endpoint}}/vocab/words/6501b27790e7d342a3485863 HTTP/1.1
Cookie: jwt={{jwt}}